import streamlit as st
import pandas as pd
from openai import OpenAI
import re
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from io import BytesIO

# --- 1. PAGE SETUP ---
st.set_page_config(page_title="Accidental PM Auditor", layout="wide", page_icon="🛡️")

# CSS: Styling for the Action Row, buttons, and Sidebar Guide
st.markdown("""
    <style>
    .stButton > button { width: 100%; border-radius: 8px; height: 3.5em; font-weight: bold; color: white !important; }
    
    /* Audit Button - Red */
    [data-testid="stHorizontalBlock"] div:nth-child(1) button { background-color: #d32f2f !important; border: none; }
    
    /* Recovery Button - Green */
    [data-testid="stHorizontalBlock"] div:nth-child(2) button { background-color: #2e7d32 !important; border: none; }
    
    /* Reset Button - Grey Background with Black Text */
    [data-testid="stHorizontalBlock"] div:nth-child(3) button { 
        background-color: #bdc3c7 !important; 
        color: #000000 !important; 
        border: 2px solid #2c3e50 !important;
    }

    .status-box { padding: 15px; border-radius: 8px; text-align: center; font-weight: bold; margin-bottom: 20px; border: 1px solid #ddd; }
    .glossary-card { background-color: #f8f9fa; padding: 15px; border-radius: 10px; border-left: 5px solid #0052cc; margin-bottom: 10px; }
    .sidebar-guide { font-size: 0.85rem; color: #333; background-color: #f0f2f6; padding: 12px; border-radius: 8px; border: 1px solid #d1d5db; }
    .mandatory { color: #d32f2f; font-weight: bold; }
    .sample-table { font-size: 0.75rem; width: 100%; border-collapse: collapse; margin-top: 10px; background-color: white; }
    .sample-table th, .sample-table td { border: 1px solid #ccc; padding: 4px; text-align: left; color: black; }
    </style>
    """, unsafe_allow_html=True)

# --- 2. SAFE SECRETS LOGIC ---
# Updated for Streamlit Cloud deployment
default_key = st.secrets.get("OPENAI_API_KEY", "")

# WORD DOC GENERATOR
def create_word_doc(domain, audit, recovery):
    doc = Document()
    title = doc.add_heading('Project Audit & Recovery Report', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    p = doc.add_paragraph()
    run = p.add_run(f'Industry Domain: {domain}')
    run.bold = True
    run.font.size = Pt(12)
    
    doc.add_heading('🕵️ Audit Findings', level=1)
    doc.add_paragraph(audit)
    
    doc.add_heading('🛠️ Recovery Roadmap', level=1)
    doc.add_paragraph(recovery)
    
    doc.add_paragraph('\n--- Generated by Accidental PM Auditor ---')
    bio = BytesIO()
    doc.save(bio)
    return bio.getvalue()

# CSV TEMPLATE GENERATOR
def get_csv_template():
    df_template = pd.DataFrame({
        "Task ID": [1, 2, 3, 4],
        "Task Name": ["Kickoff Meeting", "Scope Definition", "Implementation", "Final Review"],
        "Start Date": ["2026-05-01", "2026-05-02", "2026-05-15", "2026-06-01"],
        "End Date": ["2026-05-01", "2026-05-10", "2026-05-30", "2026-06-02"],
        "Resource": ["Lead PM", "Analyst", "Developer", "Client Team"],
        "Predecessor": ["None", "1", "2", "3"]
    })
    return df_template.to_csv(index=False).encode('utf-8')

st.title("🛡️ Accidental PM Auditor")
st.write("### *Logic Validation & Practical Recovery*")

# --- 3. SIDEBAR ---
with st.sidebar:
    st.header("Auditor Control")
    # Users can still override the key manually if they wish
    api_key = st.text_input("OpenAI API Key", value=default_key, type="password")
    
    project_context = st.selectbox(
        "Project Domain", 
        ["IT/Software", "Construction", "General Operations", "Marketing & Creative", "Event Management"]
    )
    
    st.download_button(
        label="📥 Download CSV Template",
        data=get_csv_template(),
        file_name="pmo_auditor_template.csv",
        mime="text/csv"
    )

    st.divider()
    st.markdown("**📖 Quick Start Guide**")
    st.markdown(f"""
    <div class="sidebar-guide">
    1. <b>File Prep:</b> Ensure your file contains these columns with <span class="mandatory">populated data</span>:
    <table class="sample-table">
        <tr><th>Task ID</th><th>Task Name</th><th>Start Date</th><th>End Date</th><th>Resource</th><th>Predecessor</th></tr>
        <tr><td>1</td><td>Kickoff</td><td>2026-05-01</td><td>2026-05-01</td><td>Sarah</td><td>None</td></tr>
        <tr><td>2</td><td>Design</td><td>2026-05-02</td><td>2026-05-10</td><td>Dave</td><td>1</td></tr>
    </table><br>
    2. <b>Select Type:</b> Set your <b>Project Domain</b> dropdown.<br><br>
    3. <b>Process:</b> Run Audit (Red), then Recovery (Green).<br><br>
    4. <b>Download Report:</b> Export findings as a professional Word Doc.<br><br>
    5. <b>Reset:</b> Use the grey button to clear the session.
    </div>
    """, unsafe_allow_html=True)

# --- 4. MAIN INTERFACE ---
uploaded_file = st.file_uploader("Upload Project Schedule (XLSX or CSV)", type=["xlsx", "csv"])

if uploaded_file and api_key:
    client = OpenAI(api_key=api_key)
    try:
        # File Handling
        if uploaded_file.name.endswith('.xlsx'):
            df = pd.read_excel(uploaded_file)
        else:
            df = pd.read_csv(uploaded_file)
            
        st.subheader("📋 Active Schedule Data")
        st.dataframe(df, use_container_width=True)
        
        col1, col2, col3 = st.columns(3)
        
        with col1:
            if st.button("🚀 EXECUTE LOGIC AUDIT"):
                with st.spinner(f"Auditing {project_context}..."):
                    schedule_data = df.to_string(index=False)
                    response = client.chat.completions.create(
                        model="gpt-4-turbo",
                        messages=[
                            {"role": "system", "content": f"Audit {project_context} schedule for logic errors. Identify missing predecessors or date conflicts. Give 0-100% score."},
                            {"role": "user", "content": schedule_data}
                        ]
                    )
                    st.session_state['audit_report'] = response.choices[0].message.content
                    st.rerun()
        
        with col2:
            if 'audit_report' in st.session_state:
                if st.button("🛠️ GENERATE RECOVERY PLAN"):
                    with st.spinner("Calculating recovery roadmap..."):
                        response = client.chat.completions.create(
                            model="gpt-4-turbo",
                            messages=[
                                {"role": "system", "content": "Create a clear 3-step recovery plan based on these audit findings. Focus on practical fixes for an Accidental PM. Do NOT include Jira tickets."},
                                {"role": "user", "content": st.session_state['audit_report']}
                            ]
                        )
                        st.session_state['recovery_plan'] = response.choices[0].message.content
                        st.rerun()
        
        with col3:
            if st.button("🗑️ RESET ALL DATA"):
                # Clears session data except for the API key
                for key in list(st.session_state.keys()):
                    if key != "OPENAI_API_KEY":
                        del st.session_state[key]
                st.rerun()

        # Display Results
        if 'audit_report' in st.session_state:
            st.divider()
            st.subheader("🕵️ Auditor's Findings")
            st.markdown(st.session_state['audit_report'])
            
        if 'recovery_plan' in st.session_state:
            st.success("### ✅ Practical Recovery Roadmap")
            st.markdown(st.session_state['recovery_plan'])
            
            # Document Generation
            word_data = create_word_doc(
                project_context, 
                st.session_state['audit_report'], 
                st.session_state['recovery_plan']
            )
            st.download_button(
                label="📥 Download Professional Report (.docx)",
                data=word_data,
                file_name=f"Audit_Recovery_Report.docx",
                mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                use_container_width=True
            )
            
    except Exception as e:
        st.error(f"Error: {e}")

# --- 5. GLOSSARY ---
st.divider()
with st.expander("📚 Accidental PM's Glossary"):
    st.markdown("""<div class="glossary-card"><strong>Predecessor:</strong> The task that must finish before the next one starts.</div>""", unsafe_allow_html=True)
    st.markdown("""<div class="glossary-card"><strong>Critical Path:</strong> The sequence of tasks that determines the project end date. Delaying any of these delays the project.</div>""", unsafe_allow_html=True)
