import streamlit as st
import pandas as pd
from openai import OpenAI
import re
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from io import BytesIO
import os

# --- 1. PAGE SETUP ---
st.set_page_config(page_title="The Empowered PM Auditor", layout="wide", page_icon="🛡️")

# CSS: Styling for The Empowered PM branding
st.markdown("""
    <style>
    .stButton > button { width: 100%; border-radius: 8px; height: 3.5em; font-weight: bold; color: white !important; }
    
    /* Audit Button - Red */
    [data-testid="stHorizontalBlock"] div:nth-child(1) button { background-color: #d32f2f !important; border: none; }
    
    /* Recovery Button - Green */
    [data-testid="stHorizontalBlock"] div:nth-child(2) button { background-color: #2e7d32 !important; border: none; }
    
    /* Reset Button - Grey Background with Black Text */
    [data-testid="stHorizontalBlock"] div:nth-child(3) button { 
        background-color: #bdc3c7 !important; 
        color: #000000 !important; 
        border: 2px solid #2c3e50 !important;
    }

    .hero-section { background-color: #f0f4f8; padding: 25px; border-radius: 15px; border-left: 10px solid #0052cc; margin-bottom: 20px; }
    .glossary-card { background-color: #f8f9fa; padding: 15px; border-radius: 10px; border-left: 5px solid #0052cc; margin-bottom: 10px; }
    .sidebar-guide { font-size: 0.85rem; color: #333; background-color: #f0f2f6; padding: 12px; border-radius: 8px; border: 1px solid #d1d5db; }
    .sample-table { font-size: 0.75rem; width: 100%; border-collapse: collapse; margin-top: 10px; background-color: white; }
    .sample-table th, .sample-table td { border: 1px solid #ccc; padding: 4px; text-align: left; color: black; }
    </style>
    """, unsafe_allow_html=True)

# --- SAFE SECRETS LOGIC ---
# Using the background secret key so it never shows in the UI
api_key = st.secrets.get("OPENAI_API_KEY", "")

# WORD DOC GENERATOR
def create_word_doc(domain, audit, recovery):
    doc = Document()
    title = doc.add_heading('The Empowered PM: Audit & Recovery Report', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run('Effective PM Practices for Everyone')
    run.italic = True
    
    doc.add_heading('🕵️ Audit Findings', level=1)
    doc.add_paragraph(audit)
    
    doc.add_heading('🛠️ Recovery Roadmap', level=1)
    doc.add_paragraph(recovery)
    
    doc.add_paragraph('\n--- Generated by The Empowered PM Auditor ---')
    bio = BytesIO()
    doc.save(bio)
    return bio.getvalue()

# --- MAIN INTERFACE HEADER ---
col_logo, col_title = st.columns([1, 4])

with col_logo:
    # UPDATED: Now looks for the .png version
    if os.path.exists("empPMlogo.png"):
        st.image("empPMlogo.png", width=150)

with col_title:
    st.title("The Empowered PM Auditor")
    st.write("### *Effective PM Practices for Everyone*")

st.markdown("""
<div class="hero-section">
    <strong>The Logic Linter for Leaders.</strong> Upload your project schedule below. 
    Our AI identifies logic bugs and dependency gaps so you can lead with absolute authority.
</div>
""", unsafe_allow_html=True)

# --- 2. SIDEBAR ---
with st.sidebar:
    st.header("Auditor Control")
    
    project_context = st.selectbox(
        "Project Domain", 
        ["IT/Software", "Construction", "General Operations", "Marketing & Creative", "Event Management"]
    )
    
    # Template download
    df_template = pd.DataFrame({
        "Task ID": [1, 2, 3],
        "Task Name": ["Kickoff", "Design", "Build"],
        "Start Date": ["2026-05-01", "2026-05-02", "2026-05-10"],
        "End Date": ["2026-05-01", "2026-05-09", "2026-05-25"],
        "Predecessor": ["None", "1", "2"]
    })
    st.download_button(
        label="📥 Download CSV Template",
        data=df_template.to_csv(index=False).encode('utf-8'),
        file_name="empowered_pm_template.csv",
        mime="text/csv"
    )

    st.divider()
    st.markdown("**📖 Quick Start Guide**")
    st.markdown("""
    <div class="sidebar-guide">
    1. <b>Upload:</b> Plan in XLSX or CSV format.<br>
    2. <b>Audit:</b> Click Red to find logic errors.<br>
    3. <b>Recover:</b> Click Green for the roadmap.<br>
    4. <b>Export:</b> Download the branded Word report.
    </div>
    """, unsafe_allow_html=True)

# --- 3. MAIN INTERFACE ---
if not api_key:
    st.error("🚨 API Key missing from Secrets. Please add OPENAI_API_KEY to Streamlit Cloud.")
    st.stop()

uploaded_file = st.file_uploader("Upload Project Schedule (XLSX or CSV)", type=["xlsx", "csv"])

if uploaded_file:
    client = OpenAI(api_key=api_key)
    try:
        df = pd.read_excel(uploaded_file) if uploaded_file.name.endswith('.xlsx') else pd.read_csv(uploaded_file)
        st.subheader("📋 Active Schedule Data")
        st.dataframe(df, use_container_width=True)
        
        col1, col2, col3 = st.columns(3)
        
        with col1:
            if st.button("🚀 EXECUTE LOGIC AUDIT"):
                with st.spinner("Analyzing schedule logic..."):
                    schedule_data = df.to_string(index=False)
                    response = client.chat.completions.create(
                        model="gpt-4-turbo",
                        messages=[{"role": "system", "content": "You are The Empowered PM Mentor. Audit this schedule for logic errors and date conflicts. Be authoritative and supportive."}, {"role": "user", "content": schedule_data}]
                    )
                    st.session_state['audit_report'] = response.choices[0].message.content
                    st.rerun()
        
        with col2:
            if 'audit_report' in st.session_state:
                if st.button("🛠️ GENERATE RECOVERY PLAN"):
                    with st.spinner("Building roadmap..."):
                        response = client.chat.completions.create(
                            model="gpt-4-turbo",
                            messages=[{"role": "system", "content": "Provide a 3-step recovery plan based on the audit. Focus on clear, high-impact fixes for a project leader."}, {"role": "user", "content": st.session_state['audit_report']}]
                        )
                        st.session_state['recovery_plan'] = response.choices[0].message.content
                        st.rerun()
        
        with col3:
            if st.button("🗑️ RESET ALL DATA"):
                for key in list(st.session_state.keys()):
                    del st.session_state[key]
                st.rerun()

        if 'audit_report' in st.session_state:
            st.divider()
            st.subheader("🕵️ Audit Findings")
            st.markdown(st.session_state['audit_report'])
            
        if 'recovery_plan' in st.session_state:
            st.success("### ✅ Your Empowered Recovery Roadmap")
            st.markdown(st.session_state['recovery_plan'])
            
            word_data = create_word_doc(project_context, st.session_state['audit_report'], st.session_state['recovery_plan'])
            st.download_button(
                label="📥 Download Branded Report (.docx)",
                data=word_data,
                file_name=f"Empowered_PM_Report.docx",
                mime="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
                use_container_width=True
            )
    except Exception as e:
        st.error(f"Error: {e}")

# --- 4. GLOSSARY ---
st.divider()
with st.expander("📚 The Empowered PM's Glossary"):
    st.markdown("""<div class="glossary-card"><strong>Logic Linter:</strong> A tool that scans your project plan for 'logic bugs' like missing links or impossible dates.</div>""", unsafe_allow_html=True)
